name = "ArrayInitializers"
uuid = "0cb05910-bdd0-407c-a038-17c783435242"
authors = ["Mark Kittisopikul <kittisopikulm@janelia.hhmi.org> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OffsetArrays"]
